# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17e9c344fc808e405f7229874a68568a42bcd6423db54620997342785bbefb08897e0f28d7e27e1ef6824d8b20b8c03acef9d7dbd8cb0fdb0c4c0bdd8dbfb560

test:
  secret_key_base: fc422e92f322d3b2e8fef9703c057fe76cc4b74e3fdc1d6677d708d1c3e93c36568d48a3f70d10a0a5abf2f1336688be8482a2e9b586a5fdee2132df17ea3503

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
